language: python
env:
  - SIMPHONY_VERSION=0.6.0
  - SIMPHONY_VERSION=master
matrix:
  allow_failures:
    - env: SIMPHONY_VERSION=master
install:
  - pip install -e git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
  - pip install Cython
  - pip install -e git+https://github.com/simphony/JYU-LB.git#egg=jyulb
  - pip install -r dev_requirements.txt
#  - sudo ./install_external.sh
  - pip install coveralls
  - python setup.py develop

script:
  - flake8 wrapper/
  - flake8 examples/
#  - flake8 .
  - coverage run -m unittest discover -s wrapper
  - coverage report

after_success:
  - coveralls
